version: 2
updates:
  # Frontend React application dependencies
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "frontend"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Auth Service Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/src/backend/auth-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "backend"
      - "auth-service"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Task Service Java/Spring dependencies
  - package-ecosystem: "maven"
    directory: "/src/backend/task-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "backend"
      - "task-service"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # File Service Go dependencies
  - package-ecosystem: "gomod"
    directory: "/src/backend/file-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "backend"
      - "file-service"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Notification Service Python dependencies
  - package-ecosystem: "pip"
    directory: "/src/backend/notification-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "backend"
      - "notification-service"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Docker image dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "ci-cd"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"