# Kubernetes Secrets Manifest v1.0.0
# Rotation Interval: 30 days
# Last Updated: 2024
# Security: AES-256-GCM encryption, RBAC enabled

apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: task-management
  labels:
    app: task-management
    component: secrets
    environment: production
  annotations:
    encryption.kubernetes.io/mode: "aes-gcm"
    secret.kubernetes.io/rotation-interval: "30d"
    secret.kubernetes.io/backup-schedule: "daily"
    secret.kubernetes.io/compliance: "soc2,iso27001"
    secret.kubernetes.io/audit-enabled: "true"
type: Opaque
data:
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_SSL_KEY: ${DB_SSL_KEY}
  DB_SSL_CERT: ${DB_SSL_CERT}
  DB_ROOT_CA: ${DB_ROOT_CA}
  DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: task-management
  labels:
    app: task-management
    component: auth
    environment: production
  annotations:
    encryption.kubernetes.io/mode: "aes-gcm"
    secret.kubernetes.io/rotation-interval: "30d"
    secret.kubernetes.io/backup-schedule: "daily"
    secret.kubernetes.io/compliance: "soc2,iso27001"
    secret.kubernetes.io/audit-enabled: "true"
type: Opaque
data:
  JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
  JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
  JWT_BLACKLIST_KEY: ${JWT_BLACKLIST_KEY}
  JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets
  namespace: task-management
  labels:
    app: task-management
    component: auth
    environment: production
  annotations:
    encryption.kubernetes.io/mode: "aes-gcm"
    secret.kubernetes.io/rotation-interval: "30d"
    secret.kubernetes.io/backup-schedule: "daily"
    secret.kubernetes.io/compliance: "soc2,iso27001"
    secret.kubernetes.io/audit-enabled: "true"
type: Opaque
data:
  AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
  AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
  AUTH0_API_KEY: ${AUTH0_API_KEY}
  AUTH0_MANAGEMENT_TOKEN: ${AUTH0_MANAGEMENT_TOKEN}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: task-management
  labels:
    app: task-management
    component: cache
    environment: production
  annotations:
    encryption.kubernetes.io/mode: "aes-gcm"
    secret.kubernetes.io/rotation-interval: "30d"
    secret.kubernetes.io/backup-schedule: "daily"
    secret.kubernetes.io/compliance: "soc2,iso27001"
    secret.kubernetes.io/audit-enabled: "true"
type: Opaque
data:
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  REDIS_TLS_KEY: ${REDIS_TLS_KEY}
  REDIS_TLS_CERT: ${REDIS_TLS_CERT}
  REDIS_AUTH_TOKEN: ${REDIS_AUTH_TOKEN}
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secrets
  namespace: task-management
  labels:
    app: task-management
    component: notifications
    environment: production
  annotations:
    encryption.kubernetes.io/mode: "aes-gcm"
    secret.kubernetes.io/rotation-interval: "30d"
    secret.kubernetes.io/backup-schedule: "daily"
    secret.kubernetes.io/compliance: "soc2,iso27001"
    secret.kubernetes.io/audit-enabled: "true"
type: Opaque
data:
  SMTP_USER: ${SMTP_USER}
  SMTP_PASSWORD: ${SMTP_PASSWORD}
  SMTP_API_KEY: ${SMTP_API_KEY}
  SMTP_TLS_CERT: ${SMTP_TLS_CERT}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: task-management
  labels:
    app: task-management
    component: storage
    environment: production
  annotations:
    encryption.kubernetes.io/mode: "aes-gcm"
    secret.kubernetes.io/rotation-interval: "30d"
    secret.kubernetes.io/backup-schedule: "daily"
    secret.kubernetes.io/compliance: "soc2,iso27001"
    secret.kubernetes.io/audit-enabled: "true"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
  AWS_KMS_KEY_ID: ${AWS_KMS_KEY_ID}