# Loki Server Configuration v2.8.0
# Enterprise-grade log aggregation and storage configuration

auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  # Enhanced timeout settings for production workloads
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  # Optimized gRPC settings for high-throughput environments
  grpc_server_max_recv_msg_size: 67108864  # 64MB
  grpc_server_max_concurrent_streams: 1000

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 3
  # Optimized chunk settings for production workloads
  chunk_idle_period: 1h
  max_chunk_age: 2h
  chunk_target_size: 1048576  # 1MB
  chunk_retain_period: 30s
  max_transfer_retries: 3
  # Write-ahead log configuration for data durability
  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: "2023-01-01"
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_entries_limit_per_query: 10000
  # Rate limiting configuration for ingestion
  ingestion_rate_mb: 50
  ingestion_burst_size_mb: 100
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 10MB

# Enhanced chunk store configuration with long-term retention
chunk_store_config:
  max_look_back_period: 26280h  # 3 years for audit logs
  chunk_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 2147483648  # 2GB
      validity: 24h

# Table manager configuration with retention policies
table_manager:
  retention_deletes_enabled: true
  retention_period: 26280h  # 3 years for audit logs
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  poll_interval: 12h

# Compactor configuration for optimized storage
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Log stream label configurations
stream_labels:
  # Application logs (1 year retention)
  app:
    matchers:
      - selector: '{environment=~".+",service=~".+",severity=~".+"}'
    retention: 8760h
    
  # System logs (30 days retention)
  system:
    matchers:
      - selector: '{namespace=~".+",container=~".+",pod=~".+"}'
    retention: 720h
    
  # Audit logs (3 years retention)
  audit:
    matchers:
      - selector: '{user=~".+",action=~".+",resource=~".+"}'
    retention: 26280h